### ISSUE TITLE
The server keeps blinding me even thought i have deleted the plugin's folders

### ISSUE THREAD

**Issue by JimmySallofficial** [8bitFra/LoginReloaded#6]
I downloaded this plugin and after i have an issue with it (read my previews issue) I deleted it but my server keeps blinding me and make me invisible! I dont recomend it at all ultil this problem is fixed.

**Comment by 8bitFra** [comment]
Try removing the effects with the dedicated command or drinking a bucket of milk. If the plugin is not present you should fix it like this.  (I believe this is not a bug but simply related to the fact that you removed the plugin without logging in, therefore without removing the effect from your account.) If you can't solve it let me know, eventually I'll try to replicate the problem.

**Comment by JimmySallofficial** [comment]
Thanks you save me. I even ask my server provider support team end they couldn´t solve it. xD Some times the solution is simple... xDDDDD You should warn peaple before download at least thought. If i didnt ask you and dont have weakly back ups i would be destroyed.

**Comment by 8bitFra** [comment]
I'm glad you solved it. Unfortunately I can't help you implementing a patch if you remove the plugin when you still have the effect on your account... Then I don't think it's necessary to report this behavior since the solution is only a method of removing the effects from a player, which is quite known and searchable online.
